DROP TABLE sql24.employee_tbl;

CREATE TABLE SQL24.EMPLOYEE_TBL(
EMP_ID INTEGER,
LAST_NAME VARCHAR(30) NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
MIDDLE_NAME VARCHAR(30),
ADDRESS VARCHAR(50),
CITY VARCHAR(20),
STATE VARCHAR(20),
ZIP VARCHAR(10),
PHONE VARCHAR(14),
PAGER VARCHAR(10),
PRIMARY KEY (EMP_ID));

CREATE TABLE SQL24.EMPLOYEE_PAY_TBL(
EMP_ID INTEGER NOT NULL REFERENCES SQL24.EMPLOYEE_TBL(EMP_ID),
POSITION VARCHAR(20),
DATE_HIRE DATE,
PAY_RATE DECIMAL,
DATE_LAST_RISE DATE,
BONUS DECIMAL);
